version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: blog-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: blog-app
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
